Create CustomPopUps.
tamokakhidze/QuizApplication pull request #3
Opened 2024-11-19 07:15 UTC by tamokakhidze

Create CustomPopUp for logging out and closing question. Create PopUpButton to use on custom pop ups. Create FinalScorePopUp which is used when you finish quiz.

2024-11-19 07:54 UTC, LukaGujejiani approved these changes

2024-11-19 07:54 UTC, LukaGujejiani commented on QuizApp/Customs/CustomPopUp.swift
> +class CustomPopUp: UIView {
Make this class final

2024-11-19 07:54 UTC, LukaGujejiani commented on QuizApp/Customs/FinalScorePopUp.swift
> +class FinalScorePopUp: UIView {
Final class

2024-11-19 08:02 UTC, AnaIoramashvili requested changes

2024-11-19 08:02 UTC, AnaIoramashvili commented on QuizApp/Customs/CustomPopUp.swift
> +class CustomPopUp: UIView {
add keyword "final"

2024-11-19 08:02 UTC, AnaIoramashvili commented on QuizApp/Customs/FinalScorePopUp.swift
> +class FinalScorePopUp: UIView {
add keyword "final"

2024-11-19 08:02 UTC, AnaIoramashvili commented on QuizApp/Customs/CustomPopUp.swift
> +class CustomPopUp: UIView {
Sorry, just saw luka wrote the same comment

2024-11-19 08:24 UTC, AnaIoramashvili approved these changes

2024-11-21 11:00 UTC, AniDzamelashvili reviewed
Good job🚀

2024-11-21 11:00 UTC, AniDzamelashvili commented on QuizApp/Customs/CustomPopUp.swift
> +        stackView.alignment = .fill
```suggestion
```

2024-11-21 11:00 UTC, AniDzamelashvili commented on QuizApp/Customs/CustomPopUp.swift
> +        stackView.alignment = .fill
It's default value for alignment

2024-11-21 11:00 UTC, AniDzamelashvili commented on QuizApp/Customs/CustomPopUp.swift
> +        stackView.axis = .horizontal
```suggestion
```

2024-11-21 11:00 UTC, AniDzamelashvili commented on QuizApp/Customs/CustomPopUp.swift
> +        stackView.axis = .horizontal
It's default value for axis

2024-11-21 11:00 UTC, AniDzamelashvili commented on QuizApp/Customs/PopupButton.swift
> +        self.contentVerticalAlignment = .center
I think contentHorizontalAlignment is by default centre, but not sure. please check for contentVerticalAlignment as well

2024-11-21 11:00 UTC, AniDzamelashvili approved these changes

2024-11-21 12:09 UTC, merged